---
apiVersion: apps/v1
kind: Deployment # Type of Kubernetes resource
metadata:
  name: hola-modules-v5 # Name of the Kubernetes resource
  labels:
    app: hola-modules
    version: v5
spec:
  replicas: 3 # Number of pods to run at any given time
  selector:
    matchLabels:
      app: hola-modules # This deployment applies to any Pods matching the specified label
      version: v5
  template: # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels: # The labels that will be applied to all of the pods in this deployment
        app: hola-modules
        version: v5
    spec: # Spec for the container which will run in the Pod
      containers:
        - name: hola-modules
          image: 033245014990.dkr.ecr.us-west-2.amazonaws.com/hola-modules:v5
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: PORT
              value: "80"
          ports:
            - containerPort: 80 # Should match the port number that the Go application listens on
          livenessProbe: # To check the health of the Pod
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe: # To check if the Pod is ready to serve traffic or not
            httpGet:
              path: /readiness
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
