apiVersion: v1
kind: Service
metadata:
  name: argocd-podinfo
  labels:
    app: argocd-podinfo
  # annotations:
  # fluxcd.io/automated: "true"
  # fluxcd.io/tag.init: regex:^3.10.*
  # fluxcd.io/tag.podinfod: semver:~3.1
spec:
  type: ClusterIP
  selector:
    app: argocd-podinfo
  ports:
    - name: http
      port: 1010
      protocol: TCP
      targetPort: http
