#!/bin/bash

# Create kubeconfig for EKS
#
#aws eks --region us-west-2 update-kubeconfig --name dev-awsk-eks-uswest2-cluster-01

# Install AWS IAM authenticator
#
#go get -u -v \
#github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator

# Install helm (v2)
# Make sure to symlink helm with
#  export PATH="/usr/local/opt/helm@2/bin:$PATH"
#
#brew install helm@2

# Deploy the Helm config and then Tiller
# You need to be in the istio-1.x folder to do this
#
#kubectl create -f install/kubernetes/helm/helm-service-account.yaml
#helm init --service-account tiller

# Install some prerequisites
#
# helm install \
# --wait \
# --name istio-init \
# --namespace istio-system \
# install/kubernetes/helm/istio-init

# Then install the Helm chart for istio
#
# helm install \
# --wait \
# --name istio \
# --namespace istio-system \
# install/kubernetes/helm/istio \
# --values install/kubernetes/helm/istio/values-istio-demo.yaml

# helm install install/kubernetes/helm/istio --name istio --namespace istio-system --set global.configValidation=false --set sidecarInjectorWebhook.enabled=false --set grafana.enabled=true --set servicegraph.enabled=true

# kubectl apply -f samples/bookinfo/networking/destination-rule-all.yaml

istioctl manifest \
  --set values.gateways.istio-ingressgateway.sds.enabled=true \
  --set values.global.k8sIngress.enabled=true \
  --set values.global.k8sIngress.enableHttps=true \
  --set values.global.k8sIngress.gatewayName=ingressgateway


istioctl manifest generate \
--set values.gateways.istio-egressgateway.enabled=false \
--set values.gateways.istio-ingressgateway.sds.enabled=true > \ istio-ingressgateway-sds.yaml


kubectl -n istio-system \
patch gateway istio-autogenerated-k8s-ingress --type=json \
-p='[{"op": "replace", "path": "/spec/servers/1/tls", "value": {"credentialName": "ingress-cert", "mode": "SIMPLE", "privateKey": "sds", "serverCertificate": "sds"}}]'

